[workspace]
resolver = "2"
members = [
    "novacli",
    "novacore",
    "native",
    "lexer",
    "vm",
    "assembler",
    "disassembler",
    "compiler",
    "common",
    "optimizer",
    "parser"
]

[profile.release]
opt-level = 3
