[workspace]
members = [
    "nova-lang",
    "native",
    "lexer",
    "vm",
    "assembler",
    "disassembler",
    "compiler",
    "common",
    "optimizer",
    "parser"
]

[profile.release]
opt-level = 3